### PR TITLE
fix: fio write to ufs error (fix #440)

### LINKED ISSUE #440: [BUG]: fio write to ufs error
FIO writing to UFS resulted in the error: File already exists: /s3-test/x1.log

### PR DESCRIPTION
**Pull request by bigbigxu**

### CODE REVIEW

File: curvine-ufs/src/opendal.rs [hunk 1]
```diff
@@ -697,30 +696,27 @@ impl FileSystem<OpendalWriter, OpendalReader> for OpendalFileSystem {
...
+
         let exist = self.exists(path).await?;
-        if exist && !_overwrite {
-            return Err(FsError::common(format!(
-                "File already exists: {}",
-                path.full_path()
-            )));
+        if !exist {
+            // If no data is written to OpenDal, no file will be created.
+            // This does not conform to POSIX semantics, so an empty file is created.
```
Comment (szbr00) [inline curvine-ufs/src/opendal.rs:706]: Create an empty file to conform to POSIX semantics

**Review by szbr9486 — APPROVED** [review]
