### PR TITLE
fix(server): when set_attr is set recursively, the directory node is …

### LINKED ISSUE #718: [BUG]: When `set_attr` is set recursively, the directory node is set to the expected attribute.

### PR DESCRIPTION
**Pull request by bigbigxu**
…set to the expected attribute (fix #718)

- Add `recursive: bool` to free RPC and API; non-recursive skips expanding directory children. Journal FreeEntry and replay carry recursive.
- Return `FreeResult` (inodes, bytes, blocks) from free instead of (). Proto: FreeRequest.recursive, FreeResponse.res (FreeResultProto).
- FsDir: unprotected_free uses stack-based traversal; only free inodes that satisfy TTL free (ttl_action==Free, ufs_exists, cv_exists).

### CODE REVIEW

File: curvine-server/src/master/meta/fs_dir.rs [hunk 1]
```diff
@@ -803,42 +803,38 @@ impl FsDir {
...
+                    opts.clone()
+                };
+                cur_inode.as_mut().set_attr(set_opts);
+                change_inodes.push(cur_inode.as_ref().clone());
+            }
+
+            match cur_inode.as_mut() {
+                Dir(_, dir) if opts.recursive => {
+                    for child in dir.children_iter() {
+                        stack.push_back(InodePtr::from_ref(child));
```
Comment (szbr00) [inline curvine-server/src/master/meta/fs_dir.rs:828]: This rewrites the recursive traversal to walk through `FileEntry` placeholders, but I do not see a regression test that applies `set_attr(recursive = true)` on a directory containing hard-link entries. The existing tests cover direct `set_attr` on a hard link and recursive `set_attr` on a normal subtree separately, but not the combination this change is fixing. Could we add one case that recursively updates a directory with `FileEntry` children and asserts the linked file inherits only the child attrs (for example owner/group/mode, but not ttl/xattr)?

Comment (bigbigxu) [reply curvine-server/src/master/meta/fs_dir.rs:828]: The recursive setting test is already included in fs_test::set_attr_recursive.
